pipelines:
  default:
    - step:
        script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp init --user $USERNAME --passwd $PASSWORD $REMOTE_DIR
            - qq && apt-get install -y -qq lftp
