# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

pool:
  name: 'MES 02 Pool'

steps:
- script: |
    apt-get update
    apt-get -qq install git-ftp
    git ftp init --user $USERNAME --passwd $PASSWORD $REMOTE_DIR
