name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  default:
    - step:
        script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp init --user $USERNAME --passwd $PASSWORD $REMOTE_DIR
            - qq && apt-get install -y -qq lftp
